### ISSUE TITLE
Column alignment in main view

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#153]
Could you align the column Auto/SyncMode on the left if it is not too much hassle ?
Probably it will need a new layout width logic !

<img width="324" alt="Screenshot_1598179041" src="https://user-images.githubusercontent.com/2428217/90976500-f090ab00-e53d-11ea-95e2-b9ee0d887a22.png">

It is currently left aligned/misaligned, depending on text length, because it is aligned to the sync icon
<img width="324" alt="Screenshot_1598178954" src="https://user-images.githubusercontent.com/2428217/90976501-f1294180-e53d-11ea-9fac-e3ecc63778dc.png">

Best regards

**Comment by Sentaroh** [comment]
I do not want to fix the width of the view, as this would create useless white space due to the number of characters depending on the language.
How about the following as a workaround?
![image](https://user-images.githubusercontent.com/4037866/90993002-03fb4f00-e5ee-11ea-8ecb-e9857c56ce54.png)
![image](https://user-images.githubusercontent.com/4037866/90993236-f85c5800-e5ee-11ea-9320-9bc632a35b89.png)

Best regards.

**Comment by PhilZ-cwm6** [comment]
Your original idea was great because we immediately see what's important: Sync Mode + Manual vs Auto
The changes in your commit makes it harder to immediately spot that important info if many tasks are configured

What about something in-between like this (pushed the patch)
<img width="324" alt="Screenshot_1598252360" src="https://user-images.githubusercontent.com/2428217/91014390-99481480-e5e9-11ea-9677-ec40771de399.png">

Nexus S
<img width="240" alt="Screenshot_1598257130" src="https://user-images.githubusercontent.com/2428217/91020825-41161000-e5f3-11ea-8a89-36ca0ccdd4d6.png">


- alignment is visually good because on same right edge with sync icon
- more room for sync task paths
- important info (sync mode, auto/manual) are just above the sync icon
- date / last status is at the end as it is the last event

Best regards

**Comment by Sentaroh** [comment]
Thank you.

Merge is now done.

Best regards.
