### ISSUE TITLE
[Feature Request] "Copy" files Incrementally

### ISSUE THREAD

**Issue by morganchenjp** [Sentaroh/SMBSync2#205]
I have a scenario as below:
1.  Have File-A, File-B on src folder of the phone.
2. Then I sync this folder using "Copy" mechanism from src folder to target folder on NAS. 
    Now both File-A, File-B on NAS now. 
3. Then I review the file on NAS, and delete File-A from NAS.  
    Now on NAS it only has File-B.
4. Create a new File-C on src folder. 
5. Then do the sync again using "Copy". 
6. The result is that , both File-A and File-C copied to target folder. 

Expectation:
Do the backup incrementally, eg, for my case, only copy new File-C to target folder. 

Thanks.

**Comment by PhilZ-cwm6** [comment]
What you are asking for is two way sync not incremental.

Two way sync is not currently implemented in release versions, but you can test it on the debug apk maybe. I never tested it personally because I never rely on two way sync tools because of the conflicts management... Even in an advanced app like FreeFileSync it is far from perfect if you don't take care. With a phone and because of the way time/date is implemented differently between storage formats, it can really lead to bad surprises even using the best tools...

One way sync is more for backups than collaboration use of folders on two sides

Best regards

**Comment by morganchenjp** [comment]
@PhilZ-cwm6 , 
Thanks for your feedback. 
My simple idea for my scenario:
May add an option that "Only sync files after last sync", then app can store a timestamp of last-time sync,  then only sync files which created/updated after this timestamp. 

thanks.

**Comment by PhilZ-cwm6** [comment]
App already has that feature if you look in advanced settings. 

Try the debug apk bundled in the sources. It has the 2 ways sync mode enabled that you are looking for. Report detailed bugs. If author or I have time, it could be completed once maybe. 

I let author follows up as I really never tested it yet

**Comment by Sentaroh** [comment]
Hi,

PhilZ-cwm6:
In the past, we tried to implement two-way synchronization in SMBSync2, but we gave up on it because of the unexpected loss of files when users make mistakes when conflicting files occur. (The description of bi-directional synchronization is a remnant of the past, so it will not work.)

We tried to implement it in SMBSync3, which is currently under development, but we gave up on it.

A conflicting file is a file that has been updated on both the master and the target since the last sync time, and it is impossible to determine which one to copy.

morganchenjp:
>"Only sync files after last sync"

Since the synchronization end time can vary greatly depending on the number of files and the confirmation of deletion and overwriting, it is not possible to use the synchronization task end time as the last synchronization end time, so it would be possible to implement it by keeping the synchronization end time for each file.
However, it is difficult to implement because unintentional overwriting of files may occur when a file with the sync end time recorded is lost.

Best regards.

**Comment by morganchenjp** [comment]
Hi, @Sentaroh , 

Maybe one possible design approach is that, 
when scan all target files, remember the latest "modified timestamp" (time-A here) 
then next time, just sync files which modified after time-A. 

Thanks.

**Comment by Sentaroh** [comment]
Hi,

In the following file update case, the update time transition of File c becomes the target of the next synchronization, and the update time of File d does not become the target of synchronization because it is before the update time of File c.

I think this is difficult to implement because it requires keeping information for each file to be exact.

Elapsed time | 0 Sec | 1 Sec | 11Sec     (wait 10Sec) | 12 Sec | 22 Sec     (Wait 10Sec) | 23 Sec | 23 Sec
-- | -- | -- | -- | -- | -- | -- | --
SMBSync2 | Sync   Start | copy   file a | confirm   overwrite | copy   file b | confirm   overwrite | copy   file c | Sync   end
Other App |   |   |   | Update   File d |   |   |  

File update time

File a | 1 Sec
-- | --
File b | 12   Sec
File c | 23   Sec
File d | 12Sec

Best regards.

**Comment by PhilZ-cwm6** [comment]
The proper way to do it would be to offer a conflict management prompt (Source/target wins) + default action + a keep both option (creates a file a-(1)) on both sides for every conflicting file.

However, I do agree with the developer. I really don't see the use of it for most people. Probably only a minority. And even that minority will stop using that feature after a while. Managing those "duplicates copies" with a "keep both" option is a real pain. I speak from expierience... And not going with a "keep both" option is asking for trouble because most Android phones do not allow setting the file time without root. 

The app already supports time/date recording in a database file for some (but not all) sync scenarios. So, it is not that hard to implement based on the sources as I looked at that part a few months back, but I also decided not to go with it.

**Comment by Sentaroh** [comment]
Hi,

> The app already supports time/date recording in a database file for some (but not all) sync scenarios.

Because there are some models for which File#setLastModified() does not work for files in app-specific directories, we have left the function to keep the last modified time in a file.

However, this method has the following disadvantages because SMBSync2 cannot keep track of file updates. I do not want to expand the scope of use for this method.
1. If you synchronize the file with SMBSync2 after it has been updated by another application, it will be recopied.
2. Files copied to SDCARD or USB-OTG by PC will be recopied when synchronized by SMBSync2.

Best regards.

**Comment by PhilZ-cwm6** [comment]
> Because there are some models for which File#setLastModified() does not work for files in app-specific directories
> 

I understand better now

> However, this method has the following disadvantages because SMBSync2 cannot keep track of file updates. I do not want to expand the scope of use for this method.
> 

I fully agree too because of all the issues limitations already mentioned

Best regards

**Comment by rickysarraf** [comment]
I was hoping for this very same feature that @morganchenjp has described. There's no reason for a 2 way sync in this use case.

You just keep a local `.smbsync` file/db with details of all the files it has synced to the target host. You could store the information on the basis of:

* file names: In which case you won't copy back future modifications
* file name checksums: In which case you will be capable to copy newer revisions of the file

So all your validation is on the master side only.


>Since the synchronization end time can vary greatly depending on the number of files and the confirmation of deletion and overwriting, it is not possible to use the synchronization task end time as the last synchronization end time, so it would be possible to implement it by keeping the synchronization end time for each file.

You only update the record in your local `.smbsync` db when the file has completed synchronization.

**Comment by rickysarraf** [comment]
![photo_2022-05-08_19-04-22](https://user-images.githubusercontent.com/65480/167298680-c2ebdac7-b4f4-4ac3-9ba3-19f6e363ebff.jpg)


I also realized that the use case can be achieved with 2 jobs. For anyone interested who lands on this issue, here's a screenshot.

**Comment by andrazek** [comment]
That's exactly what I was looking for as well. No need for 2-way sync, just a way to backup the newely taken photos to network folder (eg. /Photos (new)/) which allows me to organize it in a proper folder later on with my computer. It does not make sense to keep all million photos on my phone (not enough space).

@rickysarraf how well it works the way you suggested? Do we need a better implementation?

**Comment by rickysarraf** [comment]
>@rickysarraf how well it works the way you suggested? Do we need a better implementation?

For the purpose of the use case I described, it serves very well. The core assumption I make is that files that are being copied to the remote server, copy successfully. With that assumption, I progress further in the 2nd rule, to move all the files in `SOURCE` to `DESTINATION`


The other beauty of `smbsync2` is that if the 1st job, i.e. `copy` fails, the 2nd job i.e. `move` is not executed.

**Comment by andrazek** [comment]
That's great. But it works only in local network. How would we make it to sync over internet, and to backup photos immediately after they are taken, just like Nextcloud works? Is there an app to cover this kind of sync (and perhaps a client for Linux)? Nextcloud isn't perfect since its content cannot be accessed over samba in local network, alternatively WebDAV can be used, but it is extremely slow.
