### ISSUE TITLE
[Feature Request] Trigger Sync on new file/image in directory 

### ISSUE THREAD

**Issue by fritz-net** [Sentaroh/SMBSync2#217]
I really like the app, however I miss triggering the sync when a new Image is taken. Other Apps offer this Feature.
This is just an Idea to make this great App even greater, if there is demand for this by multiple people (not just me).

As far as I know apps can monitor folders and are notified when a file was added.

**Comment by Sentaroh** [comment]
Hi,

Since keeping track of file additions/deletions/updates requires the app to be in a constant state of operation, which consumes system resources and battery, we decided not to implement it during SMBSync development.

If you want to start synchronization when a file is added, deleted, or updated, please consider using an automated application such as TASKER to detect and start synchronization.

Please refer to "3. Connexion with external applications" in the following PDF for a sample of how to start synchronization from TASKER.
https://drive.google.com/file/d/1a8CTRu9xoCD74Qn0YZxzry-LHxQ8j7dE/view?usp=sharing

Best regards.
