### ISSUE TITLE
Translating help files

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#223]
Hi,

To help translate the help files, should I edit the *.md files or I must also edit the html ?

Thank you and best regards

**Comment by Sentaroh** [comment]
Hi,

At first I thought of a way to convert the MarkDown file to html in the application, but I gave up because I couldn't get the html conversion right.
(https://github.com/myabc/markdownj)

Please follow the steps below to update the file
1.Edit the MarkDown file
2.Export the Markdown file to HTML (without styles) with Typora
3. Move the exported HTML file to SMBSync2/src/main/assets directory

Best regards.
